stages:
  - stats

gitstats:
  stage: stats
  tags:
    - python3
    - gitstats
    - progstats
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - gitstats-gen
